#!/bin/bash

for d in $(find . -maxdepth 1 -type d|grep -v lost+found|grep -v \.Trash|cut -b 3-|sort)
do 
	mp=$(grep $d /etc/fstab|cut -d ' ' -f 2)
	[[ -z $mp ]] && echo $d "[$mp]" '*** NOT MOUNTPOINT ***' && continue
	[[ $(findmnt $mp) ]] && echo $d "[$mp]" 'OK' && continue
	echo $d '*** NOT DETECTED ***'
done
