#!/bin/bash

printsyntax () {
	echo $(basename $0) '<conf>'
	echo
	echo with conf:
	echo -e "\t1i  = 1: internal scale1"
	echo -e "\t1i+ = 1: internal scale+"
	echo -e "\t1e  = 1: external"
	echo -e "\t2l  = 2: internal scale1, external left"
	echo -e "\t2l+ = 2: internal scale+, external left"
	echo -e "\t2r  = 2: internal scale1, external right"
	echo -e "\t2r+ = 2: internal scale+, external rigth"

	exit 1
}

intmon="$(xrandr |grep connected|grep -v disconnected |head -n 1|cut -d ' ' -f 1)"
extmon="$(xrandr |grep connected|grep -v disconnected |grep -v $intmon|cut -d ' ' -f 1)"

if [ "$1" = "" ]
then 
	printsyntax
fi

case $1 in
	1i)
		xrandr --output $extmon --off --output $intmon --auto --scale 1x1
		;;
	1i+)
		xrandr --output $extmon --off --output $intmon --auto --scale 0.8x0.8
		;;
	1e)
		[[ ! "$extmon" = "" ]] && xrandr --output $extmon --auto --output $intmon --off --scale 1x1
		;;
	2l)
		[[ ! "$extmon" = "" ]] && xrandr --output $extmon --auto --left-of $intmon  --output $intmon --auto --scale 1x1
		;;
	2l+)
		[[ ! "$extmon" = "" ]] && xrandr --output $extmon --auto --left-of $intmon  --output $intmon --auto --scale 0.7x0.7
		;;
	2r)
		[[ ! "$extmon" = "" ]] && xrandr --output $extmon --auto --right-of $intmon  --output $intmon --auto --scale 1x1 
		;;
	2r+)
		[[ ! "$extmon" = "" ]] && xrandr --output $extmon --auto --right-of $intmon  --output $intmon --auto --scale 0.7x0.7
		;;
	*)
		printsyntax
esac
