#!/bin/bash

printsyntax () {
	echo $(basename $0) '<conf>'
	echo
	echo with conf:
	echo -e "\to   = 1: internal scale1"
	echo -e "\to+  = 1: internal scale+"
	echo -e "\tO   = 1: external"
	echo -e "\tOo  = 2: internal scale1, external left"
	echo -e "\tOo+ = 2: internal scale+, external left"
	echo -e "\toO  = 2: internal scale1, external right"
	echo -e "\to+O = 2: internal scale+, external rigth"

	exit 1
}

intmon="$(xrandr |grep connected|grep -v disconnected |head -n 1|cut -d ' ' -f 1)"
extmon="$(xrandr |grep connected|grep -v disconnected |grep -v $intmon|cut -d ' ' -f 1)"
echo Detected
echo extmon: $(xrandr |grep $extmon)
echo intmon: $(xrandr |grep $intmon)

if [ "$1" = "" ]
then 
	printsyntax
fi

plusfac="0.8x0.8"
case $1 in
	o)
		xrandr --output $extmon --off --output $intmon --auto --scale 1x1
		;;
	o+)
		xrandr --output $extmon --off --output $intmon --auto --scale $plusfac
		;;
	O)
		[[ ! "$extmon" = "" ]] && xrandr --output $extmon --auto --output $intmon --off --scale 1x1
		;;
	Oo)
		[[ ! "$extmon" = "" ]] && xrandr --output $extmon --auto --left-of $intmon  --output $intmon --auto --scale 1x1
		;;
	Oo+)
		[[ ! "$extmon" = "" ]] && xrandr --output $extmon --auto --left-of $intmon  --output $intmon --auto --scale $plusfac
		;;
	oO)
		[[ ! "$extmon" = "" ]] && xrandr --output $extmon --auto --right-of $intmon  --output $intmon --auto --scale 1x1 
		;;
	o+O)
		[[ ! "$extmon" = "" ]] && xrandr --output $extmon --auto --right-of $intmon  --output $intmon --auto --scale $plusfac
		;;
	*)
		printsyntax
esac
