#!/bin/bash

subdir='selection'
[[ -z $1 ]] && exit

dir=$(dirname $1)/$subdir
[[ -e $dir ]] && [[ ! -d $dir ]] && echo -e "Error: \'$dir\' is not a dir\nplease remove it." && read k
[[ ! -e $dir ]] && mkdir $dir
[[ ! -e $dir ]] && echo "Error: creation of '$dir' failed" && read k

mv $1 $dir

echo $*
echo $dir

read k


