#!/bin/bash
[[ -d $1 ]] && cd $1
[[ -f $1 ]] && cd $(dirname $1) 
[[ ! -f exif_db.txt ]] && echo -e "ERROR: missing exif_db.txt\n       try to create exif_db with photo_mkexifdb\n" && exit 1
photo_exiffind -tag ISO -nval 1600-50000 2>/dev/null |grep JPG >HiISO_1.txt
cat HiISO_1.txt |sed -e 's/JPG.*$/JPG/'|sed -e 's/^.*IMT/IMT/' |sort|uniq >HiISO_2.txt
mkdir HiISO
cd HiISO
cp ../HiISO_2.txt .
for f in $(cat HiISO_2.txt ) 
do
	for v in $(ls ../|grep $(echo $f|sed -e 's/.JPG//'))
	do 
		mv ../$v . 
	done
done

