#!/bin/bash
unalias -a

for r in $(ls |grep ".CR2$")
do
	p="$r".pp3
	j=rjpg_rt/"$(echo $r|sed -e 's/.CR2/rt.jpg/')"
	if [ ! -f $p ] 
	then
		echo $f need processing
	else
		if [ ! -f $j ] 
		then
			echo $p need processing
		else
			if [ $p -nt $j ]
			then
				echo $p need processing
			fi

		fi	
	fi 
done

