#!/bin/bash

for img in *.jpg *.JPG 
do
	#echo $img
	icd=$(metacam "$img" |grep -i "image creation date"|cut -c 31-)
	imtime=$(echo $icd|cut -c "12-13 15-16 18-19")
	imdate=$(echo $icd|cut -c "9-10 6-7 3-4")
	if [ ! "$imdate" = "000000" -a ! $imtime = "0000" ]
	then 
		if [ $1 = "-s" ]
		then
			echo mv "$img" "$imdate"_"$imtime".jpg
		else
			mv "$img" "$imdate"_"$imtime".jpg
		fi
	else
		echo Skipping $img
	fi
done
