#!/bin/bash 
odir=/data/bin/sysconfs
[[ ! "$UID" = "0" ]] && exit 1

fname="$(whoami)"_$(basename $0|sed -e  's/^save_//').dump

[ ! -d $odir ] && echo nodir && exit 1

newer=$(find $odir -name $fname -ctime 1|wc -l)
#[[ ! -f /$fname ]] && newer="0" 

#echo $newer
[ "$newer" = "0" ] && lsmod >$odir/$fname

