#!/bin/bash

printHelpMsg () {
	echo -e "\n Syntax: $(basename $0) [dir] [-s] [-u] [-um] [-h]" \
	"\n\tdir\t:\tspecify working dir" \
	"\n\t-s\t:\tscan dir and prepare lists " \
	"\n\t-u\t:\tupdate images exif using lists " \
	"\n\t-m\t:\tupdate images exif using manual lists " \
	"\n\t-v\t:\tverbose " \
	"\n\nKnown manual lists: "\
	"\n\tLensLeitzElmarit28.txt" \
	"\n\tLensLeitzElmarit35.txt" \
	"\n\tLensLeitzElmarit90.txt" \
	"\n\tLensLeitzSummicron50.txt" \
	"\n\tLensM42Fujinon75-150.txt" \
	"\n\tLensM2Helios44.txt" \
	"\n\tLensM42Jupiter9.txt" \
	"\n\tLensM42Zenitar16.txt" 
}

verboseMsg () {
	[[ "$verbose" = "1" ]] && echo $1
}

progress () {
	echo -e $1 "\r   $((prognow*100/progtotal)) %    \r"
}


add2LensList() {
	lenstrue="0"
	for ltag in $(echo $lenstags|tr '§' '\n');
	do
		#echo $ltag
		if [[ "$lenstrue" = "0" ]] 
		then
			echo $imexif|grep -q $ltag 
			lenstrue="$?"
		fi
	done

	if [[ "$lenstrue" = "0" ]] 
	then 
		echo $img >>$lenslist
	fi 
}

set_FD28_20 () {
	lenstags='FocalLength:28.0mm' #exif tags to recognize 
	lenslist="LensCanonFD28_F2.0.txt" #images list for this lens
 	lensmodel="Canon FD 28 mm 1:2.0" 
	lensflength="28.0 mm" 
	lensftype="Fixed"
	lensmaflength="$lensflength" 
	lensmiflength="$lensflength" 
	lensaperture="2.0"
}


set_FD28_50 () { ### adapter with wrong aperture
	lenstags='Aperture:2.0§FocalLength:28.0mm' #exif tags to recognize 
	lenslist="LensCanonFD28_F2.0.txt" #images list for this lens
 	lensmodel="Canon FD 28 mm 1:2.0" 
	lensflength="28.0 mm" 
	lensftype="Fixed"
	lensmaflength="$lensflength" 
	lensmiflength="$lensflength" 
	lensaperture="2.0"
} 

set_FL55_12 () {
	lenstags='Aperture:1.2§FocalLength:55.0mm' #exif tags to recognize 
	lenslist="LensCanonFL55_F1.2.txt" #images list for this lens
 	lensmodel="Canon FL 55 mm 1:1.2" 
	lensflength="55.0 mm" 
	lensftype="Fixed"
	lensmaflength="$lensflength" 
	lensmiflength="$lensflength" 
	lensaperture="1.2"
}

set_FD85_12 () {
	lenstags='Aperture:1.2§FocalLength:85.0mm' #exif tags to recognize 
	lenslist="LensCanonFD85_F1.2.txt" #images list for thislens
 	lensmodel="Canon FD 85 mm 1:1.2 L newFD" 
	lensflength="85.0 mm" 
	lensftype="Fixed"
	lensmaflength="$lensflength" 
	lensmiflength="$lensflength" 
	lensaperture="1.2"
}

set_FD100_20 () {
	lenstags='Aperture:2.0§FocalLength:100.0mm' #exif tags to recognize 
	lenslist="LensCanonFD100_F2.0.txt" #images list for this lens
 	lensmodel="Canon FD 100 mm 1:2.0" 
	lensflength="100.0 mm" 
	lensftype="Fixed"
	lensmaflength="$lensflength" 
	lensmiflength="$lensflength" 
	lensaperture="2.0"
}

set_FD35-105_35 () {
	lenstags='Aperture:3.5§FocalLength:105.0mm' #exif tags to recognize 
	lenslist="LensCanonFD35-105_F3.5.txt" #images list for this lens
	lenslist="LensCanonFD35-105_F3.5.txt" #images list for this lens
 	lensmodel="Canon FD 35-105 mm 1:3.5" 
	lensflength="105.0 mm" 
	lensftype="Zoom"
	lensmaflength="$lensflength" 
	lensmiflength="35.0 mm" 
	lensaperture="3.5"
}

set_FD135_20 () {
	lenstags='Aperture:2.0§FocalLength:135.0mm' #exif tags to recognize 
	lenslist="LensCanonFD135_F2.0.txt" #images list for this lens
 	lensmodel="Canon FD 135 mm 1:2.0" 
	lensflength="135.0 mm" 
	lensftype="Fixed"
	lensmaflength="$lensflength" 
	lensmiflength="$lensflength" 
	lensaperture="2.0"
}

set_LeitzElm28_28 () {
	lenslist="LensLeitzElmarit28.txt" #images list for this lens
 	lensmodel="Leitz Elmarit 28 mm 1:2.8" 
	lensflength="28.0 mm" 
	lensftype="Fixed"
	lensmaflength="$lensflength" 
	lensmiflength="$lensflength" 
	lensaperture="2.8"
}

set_LeitzElm35_28 () {
	lenslist="LensLeitzElmarit35.txt" #images list for this lens
 	lensmodel="Leitz Elmarit 35 mm 1:2.8" 
	lensflength="35.0 mm" 
	lensftype="Fixed"
	lensmaflength="$lensflength" 
	lensmiflength="$lensflength" 
	lensaperture="2.8"
}

set_LeitzElm90_28 () {
	lenslist="LensLeitzElmarit90.txt" #images list for this lens
 	lensmodel="Leitz Elmarit 90 mm 1:2.8" 
	lensflength="90.0 mm" 
	lensftype="Fixed"
	lensmaflength="$lensflength" 
	lensmiflength="$lensflength" 
	lensaperture="2.8"
}

set_LeitzSum50_20 () {
	lenslist="LensLeitzSummicron50.txt" #images list for this lens
 	lensmodel="Leitz Summicron 50 mm 1:2.0" 
	lensflength="50.0 mm" 
	lensftype="Fixed"
	lensmaflength="$lensflength" 
	lensmiflength="$lensflength" 
	lensaperture="2.0"
}

set_Fujinon75-150 () {
	lenslist="LensM42Fujinon75-150.txt" #images list for this lens
 	lensmodel="Fujinon EBC 75-150 mm 1:4.5" 
	lensflength="150.0 mm" 
	lensftype="Zoom"
	lensmaflength="150.0 mm" 
	lensmiflength="75.0 mm" 
	lensaperture="4.5"
}
set_Helios44_20 () {
	lenslist="LensM42Helios44.txt" #images list for this lens
 	lensmodel="Helios 44M-4 2/58" 
	lensflength="58.0 mm" 
	lensftype="Fixed"
	lensmaflength="$lensflength" 
	lensmiflength="$lensflength" 
	lensaperture="2.0"
}

set_Jupiter85_20 () {
	lenslist="LensM42Jupiter9.txt" #images list for this lens
 	lensmodel="Jupiter9 85mm f/2 MC" 
	lensflength="85.0 mm" 
	lensftype="Fixed"
	lensmaflength="$lensflength" 
	lensmiflength="$lensflength" 
	lensaperture="2.0"
}
set_Zenitar16_28 () {
	lenslist="LensM42Zenitar16.txt" #images list for this lens
 	lensmodel="MC Zenitar-M2.8/16" 
	lensflength="16.0 mm" 
	lensftype="Fixed"
	lensmaflength="$lensflength" 
	lensmiflength="$lensflength" 
	lensaperture="2.8"
}

set_Leitz () {
	lenstags='Aperture:1.4§FocalLength:50.0mm' #exif tags to recognize 
	lenslist="LensLeitz.txt" #images list for this lens
}

set_M42 () {
	lenstags='Aperture:2.0§FocalLength:50.0mm' #exif tags to recognize 
	lenslist="LensM42.txt" #images list for this lens
}

cleanLensList () {
	if [[ -f $lenslist ]]
	then 
		mv $lenslist "$lenslist".bak
		[[ -f "$lenslist".bak ]] && cat "$lenslist".bak|sort|uniq >$lenslist
		[[ -f "$lenslist".bak ]] && rm "$lenslist".bak
	fi
}

fixImgExifs () {
	if [[ -f $lenslist ]]
	then
		for f in $(cat $lenslist)
		do
		[[ -f $f ]] && [[ ! -z "$lensmodel" ]] && echo -e "$f\t updating exif" && exiftool -q -P -overwrite_original \
				-LensModel="$lensmodel" \
				-LensType="$lensmodel" \
				-FocalType="$lensftype" \
				-FocalLength="$lensflength" \
				-MaxFocalLength="$lensmaflength" \
				-MinFocalLength="$lensmiflength" \
				-TargetAperture="$lensaperture" \
				-ApertureValue="$lensaperture" \
				-MaxAperture="$lensaperture" \
				$f 
		done
	fi	
}

cleanLists () {
	set_FD28_20; cleanLensList 
	set_FD28_50; cleanLensList 
	set_FL55_12; cleanLensList 
	set_FD85_12; cleanLensList 
	set_FD100_20; cleanLensList 
	set_FD35-105_35; cleanLensList  
	set_FD135_20; cleanLensList  
	set_Leitz; cleanLensList #generic list for Leitz adapter
	set_M42; cleanLensList  #generic list for m42 adapter
}


### START HERE ###############################################
echo $(basename $0) 0.1

source $(dirname $0)/bash_funcs
checkCommand exiftool

workdir="."
printhelp="0"
scan="0"
update="0"
updatemanual="0"

while [[ ! "$1" == "" ]]
do
	[[ -d $1 ]] && workdir="$1" 
	[[ "$1" == "-s" ]] && scan="1"
	[[ "$1" == "-u" ]] && update="1"
	[[ "$1" == "-m" ]] && updatemanual="1"
	[[ "$1" == "-v" ]] && verbose="1"
	[[ "$1" == "-h" || "$1" = "-help" ]] && printhelp="1"
	shift
done

verboseMsg "scan=$scan;update=$update;updatemanual=$updatemanual" 

[[ "$scan" = "0" && "$update" = "0" && "$updatemanual" = "0" ]] && printHelpMsg && exit 1

verboseMsg "printhelp=$printhelp" 
[[ printhelp = "1" ]] && printHelpMsg && exit 1

progtotal="$(ls *.JPG *.jpg 2> /dev/null|wc -w)"
prognow="0"

[[ ! "$workdir" = "." ]] && cd $workdir && verboseMsg $workdir
verboseMsg "$(pwd)" 

### scan files for lens identification ######################
if [[ "$scan" = "1" ]]
then
	echo "Analyzing images ($progtotal)"
	for f in $(ls *.JPG *.CR2 2> /dev/null)
	do
		img=$f
		verboseMsg $f
		imexif=$(exiftool $img|tr -d ' ')
		prognow=$((prognow+1))
		progress -n 
		## check every lens tag to identify and add to lens list
		set_FD28_20; add2LensList 
		#set_FD28_50; add2LensList 
		set_FL55_12; add2LensList 
		set_FD85_12; add2LensList 
		set_FD100_20; add2LensList 
		set_FD35-105_35; add2LensList  
		set_FD135_20; add2LensList  
		set_Leitz; add2LensList  
		set_M42; add2LensList  
	done

	cleanLists
fi

if [[ "$update" = "1" ]]
then
	cleanLists

	# fix exif for every image found in each lens list  
	set_FD28_20; fixImgExifs
	#set_FD28_50; fixImgExifs
	set_FL55_12; fixImgExifs
	set_FD85_12; fixImgExifs
	set_FD100_20; fixImgExifs
	set_FD35-105_35; fixImgExifs
	set_FD135_20; fixImgExifs
fi


if [[ "$updatemanual" = "1" ]]
then
	cleanLists

	# fix exif for every image found in each lens manual list  
	set_LeitzElm28_28; fixImgExifs
	set_LeitzElm35_28; fixImgExifs
	set_LeitzSum50_20; fixImgExifs
	set_LeitzElm90_28; fixImgExifs
	set_Helios44_20; fixImgExifs
	set_Jupiter85_20; fixImgExifs
	set_Zenitar16_28; fixImgExifs
	set_Fujinon75-150; fixImgExifs
	exit 0
fi

