# Inserts a blank line between shell prompts
add_newline = true

# Replace the "❯" symbol in the prompt with "➜"
# Change colors

[character]                            # The name of the module we are configuring is "character"
success_symbol = "[❯](bold green)"     # The "success_symbol" segment is being set to "➜" with the color "bold green"

[username]
style_user = "green bold"
style_root = "red bold"
format = "[$user❯]($style) "
disabled = false
show_always = true

[env_var.kernelVersion]
style = "white"
variable = "kernelVersion"

[directory]
style = "white bold"
truncation_length = 3
truncation_symbol = "…/"

